package com.bressio.rendezvous.scenes;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Screen;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.badlogic.gdx.maps.tiled.TiledMap;
import com.badlogic.gdx.maps.tiled.TmxMapLoader;
import com.badlogic.gdx.maps.tiled.renderers.OrthogonalTiledMapRenderer;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.physics.box2d.Box2DDebugRenderer;
import com.badlogic.gdx.physics.box2d.World;
import com.badlogic.gdx.utils.viewport.FitViewport;
import com.badlogic.gdx.utils.viewport.Viewport;
import com.bressio.rendezvous.entities.Player;
import com.bressio.rendezvous.entities.objects.EntityObject;
import com.bressio.rendezvous.entities.tiles.Loot;
import com.bressio.rendezvous.events.InputTracker;
import com.bressio.rendezvous.events.RendezvousController;
import com.bressio.rendezvous.events.WorldContactListener;
import com.bressio.rendezvous.forge.WorldBuilder;
import com.bressio.rendezvous.graphics.ResourceHandler;
import com.bressio.rendezvous.gui.HUD;
import com.bressio.rendezvous.gui.LootInterface;
import com.bressio.rendezvous.gui.MatchMap;
import com.bressio.rendezvous.gui.PauseMenu;
import com.bressio.rendezvous.languages.Internationalization;
import com.bressio.rendezvous.scheme.PhysicsAdapter;

import java.util.ArrayList;

import static com.bressio.rendezvous.scheme.PhysicsAdapter.*;
import static com.bressio.rendezvous.scheme.PlayerSettings.*;

public class Match implements Screen {

    public enum GameState {
        RUNNING, PAUSED, TACTICAL, LOOTING
    }

    // game
    private SpriteBatch batch;
    private Internationalization i18n;
    private ResourceHandler resources;

    // rendering
    private OrthographicCamera camera;
    private Viewport viewport;
    private HUD hud;
    private PauseMenu pause;
    private LootInterface loot;
    private MatchMap matchMap;
    private OrthogonalTiledMapRenderer renderer;
    private OrthogonalTiledMapRenderer overRenderer;
    private Box2DDebugRenderer collisionDebugRenderer;
    private int cameraZoom = 1;

    // world
    private World world;
    private WorldBuilder worldBuilder;
    private Player player;
    private TmxMapLoader mapLoader;
    private TiledMap map;
    private TiledMap overMap;
    private TextureAtlas atlas;

    // events
    private InputTracker input;
    private GameState state;
    private RendezvousController rendezvousController;

    Match(SpriteBatch batch) {
        this.batch = batch;
        loadResources();
        setupCamera();
        setupRenderer();
        setupCursor();
        forgeWorld();
        setupInputTracker();
    }

    private void loadResources() {
        resources = new ResourceHandler();
        resources.loadMatchResources();
        atlas = resources.getTextureAtlas(ResourceHandler.TextureAtlasPath.ENTITY_ATLAS);
        mapLoader = new TmxMapLoader();
        map = resources.getTiledMap(ResourceHandler.TiledMapPath.TILEMAP);
        overMap = resources.getTiledMap(ResourceHandler.TiledMapPath.OVER_TILEMAP);
        i18n = new Internationalization();
    }

    private void setupCamera() {
        camera = new OrthographicCamera();
        viewport = new FitViewport(pScale(GAME_WIDTH) * cameraZoom, pScale(GAME_HEIGHT) * cameraZoom, camera);
        viewport.apply();
        hud = new HUD(this);
        pause = new PauseMenu(this);
        matchMap = new MatchMap(this);
        camera.position.set(pScale((float) Math.sqrt(MAP_AREA)), pScale((float) Math.sqrt(MAP_AREA)), 0);
        camera.update();
    }

    private void setupRenderer() {
        renderer = new OrthogonalTiledMapRenderer(map, PhysicsAdapter.getScale());
        overRenderer = new OrthogonalTiledMapRenderer(overMap, PhysicsAdapter.getScale());
        collisionDebugRenderer = new Box2DDebugRenderer();
        state = GameState.RUNNING;
    }

    private void setupCursor() {
        setCursor(ResourceHandler.PixmapPath.MATCH_CURSOR, true);
    }

    private void forgeWorld() {
        world = new World(GRAVITY, true);
        worldBuilder = new WorldBuilder(this);
        player = new Player(this, 32, 5, 10, worldBuilder.getPlayerSpawnPoint());
        world.setContactListener(new WorldContactListener());
        rendezvousController = new RendezvousController(this);
    }

    private void setupInputTracker() {
        input = new InputTracker(camera);
        Gdx.input.setInputProcessor(input);
    }

    private void updateCamera() {
        // smoothly moves the camera to the player's position with an offset generated by the mouse input
        camera.position.lerp(new Vector3(
                player.getBody().getPosition().x + (float)input.getRelativeX() / 500,
                player.getBody().getPosition().y - (float)input.getRelativeY() / 500,
                0), 0.05f);
        // the camera position is rounded to avoid artifacts on unfiltered textures
        camera.position.set((float) ((double) Math.round(camera.position.x * 100d) / 100d),
                (float) ((double) Math.round(camera.position.y * 100d) / 100d), camera.position.z);
        camera.update();
        renderer.setView(camera);
        overRenderer.setView(camera);
    }

    private void update(float delta) {
        if (state == GameState.RUNNING || state == GameState.TACTICAL || state == GameState.LOOTING) {
            world.step(1 / 60f, 6, 2);
            rendezvousController.update(delta);
            player.update(delta);
            matchMap.update(delta, player.getBody().getPosition());
            updateCamera();
        }

    }

    private void lateUpdate(float delta) {
        input.update();
        handlePauseMenu(delta);
        handleMatchMap(delta);
        handleInventoryInput(delta);
        updateLoot(delta);
    }

    private void handlePauseMenu(float delta) {
        if (InputTracker.isPressed(InputTracker.ESC)){
            if (state == GameState.RUNNING || state == GameState.TACTICAL || state == GameState.LOOTING) {
                input.resetAllKeys();
                Gdx.input.setInputProcessor(pause.getStage());
                setCursor(ResourceHandler.PixmapPath.MENU_CURSOR, false);
                setState(GameState.PAUSED);
            }
        }
    }

    public void handleLootInterface(float delta, ArrayList<EntityObject> items) {
        if (InputTracker.isPressed(InputTracker.E)){
            if (state == GameState.RUNNING || state == GameState.TACTICAL) {
                loot = new LootInterface(this, items, player.getInventory().getItems());
                input.resetAllKeys();
                Gdx.input.setInputProcessor(loot.getStage());
                setCursor(ResourceHandler.PixmapPath.MENU_CURSOR, false);
                setState(GameState.LOOTING);
            }
        }
    }

    private void handleMatchMap(float delta) {
        if (InputTracker.isPressed(InputTracker.M)){
            if (state == GameState.RUNNING) {
                input.resetSecondaryKeys();
                setCursor(ResourceHandler.PixmapPath.MENU_CURSOR, false);
                setState(GameState.TACTICAL);
            } else if (state == GameState.TACTICAL) {
                input.resetSecondaryKeys();
                setCursor(ResourceHandler.PixmapPath.MATCH_CURSOR, true);
                setState(GameState.RUNNING);
            }
        }
    }

    private void handleInventoryInput(float delta) {
        if (InputTracker.isPressed(InputTracker.NUM_1)) {
            hud.switchSelectedSlot(0);
        } else if (InputTracker.isPressed(InputTracker.NUM_2)) {
            hud.switchSelectedSlot(1);
        } else if (InputTracker.isPressed(InputTracker.NUM_3)) {
            hud.switchSelectedSlot(2);
        } else if (InputTracker.isPressed(InputTracker.NUM_4)) {
            hud.switchSelectedSlot(3);
        } else if (InputTracker.isPressed(InputTracker.NUM_5)) {
            hud.switchSelectedSlot(4);
        } else if (InputTracker.isPressed(InputTracker.NUM_6)) {
            hud.switchSelectedSlot(5);
        }
        if (input.isScrolling() != 0) {
            hud.switchSelectedSlot(input.isScrolling() == 1);
            input.resetScrollAmount();
        }
    }

    public TextureAtlas getAtlas() {
        return atlas;
    }

    public ResourceHandler getResources() {
        return resources;
    }

    public World getWorld() {
        return world;
    }

    public TiledMap getMap() {
        return map;
    }

    public SpriteBatch getBatch() {
        return batch;
    }

    public Internationalization getI18n() {
        return i18n;
    }

    public HUD getHud() {
        return hud;
    }

    public Player getPlayer() {
        return player;
    }

    private void renderPauseMenu(float delta) {
        batch.setProjectionMatrix(pause.getStage().getCamera().combined);
        pause.getStage().draw();
    }

    private void renderLootInterface(float delta) {
        batch.setProjectionMatrix(loot.getStage().getCamera().combined);
        loot.getStage().draw();
        loot.getUpperStage().draw();
    }

    private void renderMap(float delta) {
        batch.setProjectionMatrix(matchMap.getStage().getCamera().combined);
        matchMap.getStage().draw();
    }

    public void setState(GameState state) {
        this.state = state;
    }

    public void delegateInputProcessor() {
        Gdx.input.setInputProcessor(input);
    }

    public void setCursor(ResourceHandler.PixmapPath pixmapPath, boolean isCentered) {
        Pixmap pixmap = resources.getPixmap(pixmapPath);
        Gdx.graphics.setCursor(Gdx.graphics.newCursor(pixmap,
                isCentered ? pCenter(pixmap.getWidth()) : 0,
                isCentered ? pCenter(pixmap.getHeight()) : 0));
    }

    private void updateLoot(float delta) {
        for (Loot loot : worldBuilder.getLoot()) {
            loot.update(delta);
        }
    }

    @Override
    public void show() {

    }

    private void renderBackgroundColor() {
        Gdx.gl.glClearColor((float)19 / 255, (float)174 / 255, (float)147 / 255, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
    }

    private void renderCollisionDebug() {
        if (DEBUG_MODE) {
            collisionDebugRenderer.render(world, camera.combined);
        }
    }

    private void renderPlayer() {
        batch.begin();
        player.draw(batch);
        batch.end();
    }

    private void renderLootInteractionButton() {
        for (Loot loot : worldBuilder.getLoot()) {
            loot.drawInteractionButton();
        }
    }

    private void renderHud(float delta) {
        batch.setProjectionMatrix(hud.getStage().getCamera().combined);
        hud.drawVignette(delta);
        hud.drawHealthBars(delta, player.getHealth(), player.getArmor());
        hud.getStage().draw();
        hud.updateHealthBars(delta, player.getHealth(), player.getArmor());
        hud.updateInventory(delta);
        if (state != GameState.TACTICAL) {
            hud.drawMinimap(delta, player.getBody().getPosition());
        }
    }

    private void renderInterface(float delta) {
        if (state == GameState.PAUSED) {
            renderPauseMenu(delta);
            pause.update(delta);
        } else if (state == GameState.TACTICAL) {
            renderMap(delta);
        } else if (state == GameState.LOOTING) {
            renderLootInterface(delta);
            loot.update(delta);
        }
    }

    @Override
    public void render(float delta) {
        update(delta);
        renderBackgroundColor();
        renderer.render();
        renderCollisionDebug();
        batch.setProjectionMatrix(camera.combined);
        renderPlayer();
        overRenderer.render();
        renderLootInteractionButton();
//        rendezvousController.render(delta);
        renderHud(delta);
        renderInterface(delta);
        lateUpdate(delta);
    }

    @Override
    public void resize(int width, int height) {
        viewport.update(width, height);
    }

    @Override
    public void pause() {

    }

    @Override
    public void resume() {

    }

    @Override
    public void hide() {

    }

    @Override
    public void dispose() {
        renderer.dispose();
        world.dispose();
        collisionDebugRenderer.dispose();
        resources.dispose();
    }
}
